"""empty message

Revision ID: e9b5362c5e95
Revises: d19f8ab7dd95
Create Date: 2016-07-20 19:49:07.694212

"""

# revision identifiers, used by Alembic.
from sqlalchemy.sql.ddl import CreateSequence

revision = 'e9b5362c5e95'
down_revision = 'd19f8ab7dd95'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('console', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

    op.execute(CreateSequence(sa.Sequence('user_seq')))
    op.execute(CreateSequence(sa.Sequence('user_preferences_seq')))

    op.alter_column("user", "id", nullable=False, server_default=sa.text("nextval('user_seq'::regclass)"))
    op.alter_column("user_preferences", "id", nullable=False, server_default=sa.text("nextval('user_preferences_seq'::regclass)"))

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.drop_table('user')
    ### end Alembic commands ###
